In [1]:
import pandas as pd

In [2]:
bowling = pd.read_csv("ODIBowling.csv")
bowling.head()

,Player,Innings Bowled In,Balls Bowled,Runs Conceded,Wickets Taken,Best Bowling In An Innings,Bowling Avg,Economy Rate,Bowling Strike Rate,Four Wickets In An Innings,Five Wickets In An Innings,200+ Wickets Taken,<35.00 Bowling Avg,<4.00 Economy Rate,<40.00 Bowling Strike Rate
0,JM Anderson (2002-2015),191,9584,7861,269,May-23,29.22,4.92,35.6,11,2,1,1,0,1
1,D Gough (1994-2006),155,8422,6154,234,May-44,26.29,4.38,35.9,10,2,1,1,0,1
2,SCJ Broad (2006-2016),121,6109,5364,178,May-23,30.13,5.26,34.3,9,1,0,1,0,1
3,A Flintoff (1999-2009),116,5496,3968,168,May-19,23.61,4.33,32.7,6,2,0,1,0,1
4,IT Botham (1976-1992),115,6271,4139,145,Apr-31,28.54,3.96,43.2,3,0,0,1,1,0

In [3]:
bowlingFeatures = bowling.drop(columns=['Best Bowling In An Innings', 'Four Wickets In An Innings', 'Five Wickets In An Innings', '200+ Wickets Taken', '<35.00 Bowling Avg', '<4.00 Economy Rate', '<40.00 Bowling Strike Rate' ])
bowlingFeatures.head()
def removeYear(x):
    return x[:-12]
def removeNA(x):
    if(x == '-'):
        return 0
    return x
bowlingFeatures["Player"] = bowlingFeatures["Player"].apply(removeYear)
bowlingFeatures["Innings Bowled In"] = bowlingFeatures["Innings Bowled In"].apply(removeNA)
bowlingFeatures["Balls Bowled"] = bowlingFeatures["Balls Bowled"].apply(removeNA).fillna(0)
bowlingFeatures["Runs Conceded"] = bowlingFeatures["Runs Conceded"].apply(removeNA)
bowlingFeatures["Wickets Taken"] = bowlingFeatures["Wickets Taken"].apply(removeNA)
bowlingFeatures["Bowling Avg"] = bowlingFeatures["Bowling Avg"].apply(removeNA)
bowlingFeatures["Economy Rate"] = bowlingFeatures["Economy Rate"].apply(removeNA)
bowlingFeatures["Bowling Strike Rate"] = bowlingFeatures["Bowling Strike Rate"].apply(removeNA)
bowlingFeatures["Player"] = bowlingFeatures["Player"].astype(str)
bowlingFeatures["Innings Bowled In"] = pd.to_numeric(bowlingFeatures["Innings Bowled In"])
bowlingFeatures["Balls Bowled"] = pd.to_numeric(bowlingFeatures["Balls Bowled"])
bowlingFeatures["Runs Conceded"] = pd.to_numeric(bowlingFeatures["Runs Conceded"])
bowlingFeatures["Wickets Taken"] = pd.to_numeric(bowlingFeatures["Wickets Taken"])
bowlingFeatures["Bowling Avg"] = pd.to_numeric(bowlingFeatures["Bowling Avg"])
bowlingFeatures["Economy Rate"] = pd.to_numeric(bowlingFeatures["Economy Rate"])
bowlingFeatures["Bowling Strike Rate"] = pd.to_numeric(bowlingFeatures["Bowling Strike Rate"])

bowlingFeatures.head()

,Player,Innings Bowled In,Balls Bowled,Runs Conceded,Wickets Taken,Bowling Avg,Economy Rate,Bowling Strike Rate
0,JM Anderson,191,9584,7861,269,29.22,4.92,35.6
1,D Gough,155,8422,6154,234,26.29,4.38,35.9
2,SCJ Broad,121,6109,5364,178,30.13,5.26,34.3
3,A Flintoff,116,5496,3968,168,23.61,4.33,32.7
4,IT Botham,115,6271,4139,145,28.54,3.96,43.2

In [4]:
batting=pd.read_csv("battingFeaturesRating.csv")
batting.head()
batting.shape

(277, 13)

In [5]:
bowlingFeatureFinal = pd.merge(batting, bowlingFeatures, how='inner', on = 'Player')
bowlingFeatureFinal=bowlingFeatureFinal.drop(columns=['Matches Played','Innings Batted','Not Outs','Runs','Highest Score','Batting Avg','Balls Faced','Strike Rate','Centuries','Half Centuries','Ducks','Rating'])
bowlingFeatureFinal = bowlingFeatureFinal.sort_values(by=['Wickets Taken'], ascending=False)
bowlingFeatureFinal = bowlingFeatureFinal.reset_index(drop=True)
bowlingFeatureFinal.head()
temp =pd.read_csv("bowlingFeatures.csv")
temp['Ratings']=temp['Ratings'].fillna(0)
bowlingFeatureFinal["Ratings"] = temp["Ratings"]
bowlingFeatureFinal["Ratings"]=bowlingFeatureFinal["Ratings"].astype(int)
bowlingFeatureFinal = bowlingFeatureFinal.sort_values(by=['Ratings'], ascending=False)
bowlingFeatureFinal = bowlingFeatureFinal.reset_index(drop=True)
bowlingFeatureFinal

,Player,Innings Bowled In,Balls Bowled,Runs Conceded,Wickets Taken,Bowling Avg,Economy Rate,Bowling Strike Rate,Ratings
0,SL Malinga,207,102732,9145,318,28.75,5.34,32.3,874
1,DW Steyn,118,60138,4893,190,25.75,4.88,31.6,861
2,Mashrafe Mortaza,200,10005,7985,257,31.07,4.78,38.9,856
3,JJ Bumrah,44,2212,1639,78,21.01,4.44,28.3,835
4,Shakib Al Hasan,192,9897,7333,247,29.68,4.44,40.0,810
5,Rashid Khan,50,26226,1708,118,14.47,3.90,22.2,800
6,TA Boult,71,3842,3326,129,25.78,5.19,29.7,800
7,Imran Tahir,89,46998,3675,151,24.33,4.69,31.1,800
8,B Kumar,94,4552,3784,99,38.22,4.98,45.9,790
9,RA Jadeja,140,7255,5905,169,34.94,4.88,42.9,770
10,M Morkel,111,5580,4595,180,25.52,4.94,31.0,750
11,CH Gayle,192,7275,5773,165,34.98,4.76,44.0,620
12,RR Pant,0,0,0,0,0.00,0.00,0.0,2
13,Hazratullah Zazai,0,0,0,0,0.00,0.00,0.0,1
14,FA Allen,4,138,131,0,0.00,5.69,0.0,1
15,S Kaul,3,162,179,0,0.00,6.62,0.0,1
16,Najmul Hossain Shanto,0,0,0,0,0.00,0.00,0.0,1
17,NGRP Jayasuriya,2,96,95,0,0.00,5.93,0.0,1
18,Abul Hasan,7,216,244,0,0.00,6.77,0.0,1
19,Fazle Mahmud,1,18,16,0,0.00,5.33,0.0,1
20,MS Chapman,0,0,0,0,0.00,0.00,0.0,1
21,C Jonker,0,0,0,0,0.00,0.00,0.0,1
22,TL Seifert,0,0,0,0,0.00,0.00,0.0,1
23,TS Kamunhukamwe,0,0,0,0,0.00,0.00,0.0,1
24,OP Stone,3,96,97,1,97.00,6.06,96.0,0
25,AJ Finch,14,158,137,2,68.50,5.20,79.0,0
26,MG Neser,2,100,120,2,60.00,7.20,50.0,0
27,AK Markram,3,48,56,2,28.00,7.00,24.0,0
28,A Balbirnie,3,60,68,2,34.00,6.80,30.0,0
29,SC Williams,1,24,30,1,30.00,7.50,24.0,0
...,...,...,...,...,...,...,...,...,...
252,CH Morris,33,1512,1415,35,40.42,5.61,43.2,0
253,CJ Chibhabha,58,1665,1615,35,46.14,5.81,47.6,0
254,KS Williamson,63,1377,1246,35,35.60,5.42,39.3,0
255,PKD Chase,24,12372,1356,34,39.88,6.57,36.4,0
256,MA Wood,35,1789,1649,34,48.50,5.53,52.6,0
257,AR McBrine,32,1605,1212,33,36.72,4.52,48.6,0
258,S Prasanna,39,19446,1767,32,55.21,5.45,60.7,0
259,BV Vitori,24,1191,1149,32,35.90,5.77,37.2,0
260,Imad Wasim,32,1341,1007,29,34.72,4.50,46.2,0
261,Aftab Alam,20,9378,772,27,28.59,4.93,34.7,0
262,KW Richardson,18,935,854,27,31.62,5.48,34.6,0
263,SPD Smith,36,1046,931,27,34.48,5.34,38.7,0
264,CR Brathwaite,27,1284,1163,26,44.73,5.43,49.3,0
265,AS Joseph,15,757,818,24,34.08,6.48,31.5,0
266,NM Lyon,15,822,662,18,36.77,4.83,45.6,0
267,Mehidy Hasan Miraz,21,1098,785,24,32.70,4.28,45.7,0
268,Nasir Hossain,43,12552,988,24,41.16,4.71,52.3,0
269,KM Jadhav,26,803,651,22,29.59,4.86,36.5,0
270,DAS Gunaratne,25,834,723,22,32.86,5.20,37.9,0
271,D Pretorius,14,6852,554,22,25.18,4.84,31.1,0
272,WP Masakadza,16,8586,734,21,34.95,5.12,40.9,0
273,JT Ball,18,947,980,21,46.66,6.20,45.0,0
274,JE Root,60,1342,1299,20,64.95,5.80,67.1,0
275,Rashid Khan,28,1414,923,20,46.15,3.91,70.7,0
276,TS Chisoro,16,768,556,20,27.80,4.34,38.4,0
277,DT Tiripano,22,9012,885,20,44.25,5.88,45.1,0
278,Yasir Shah,18,951,807,19,42.47,5.09,50.0,0
279,PVD Chameera,23,8946,796,19,41.89,5.33,47.1,0
280,Faheem Ashraf,16,573,409,18,22.72,4.28,31.8,0
281,Ariful Haque,1,18,17,0,0.00,5.66,0.0,0

In [6]:
ratedPlayerCount = len(bowlingFeatureFinal[bowlingFeatureFinal.Ratings > 0].index)


#Define training and testing data
X_train = bowlingFeatureFinal.drop(columns=['Player', 'Ratings'])
X_test = X_train.iloc[ratedPlayerCount:,:]
X_train = X_train.iloc[:ratedPlayerCount,:]

#store ratings in y_train
y_train = bowlingFeatureFinal['Ratings']
y_train = y_train.iloc[:ratedPlayerCount]

In [7]:
from sklearn.ensemble import RandomForestRegressor 

regr = RandomForestRegressor(max_depth=2, random_state=0, n_estimators=100)
regr.fit(X_train, y_train)
print(regr.feature_importances_)
RFresults = regr.predict(X_test)
'''
clf = RandomForestClassifier(n_estimators=100, max_depth=2, random_state=0)
clf = clf.fit(X_train, y_train)
RFresults = clf.predict(X_test)'''

bowlingFeatureFinal["Ratings"][ratedPlayerCount:] = RFresults

[0.11906968 0.15951926 0.24779366 0.17856495 0.15259304 0.01028243
 0.13217699]

C:\Users\parek\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':

In [8]:
bowlingFeatureFinal = bowlingFeatureFinal.sort_values(by=['Ratings'], ascending=False)
bowlingFeatureFinal = bowlingFeatureFinal.reset_index(drop=True)
bowlingFeatureFinal.to_csv('bowlingFeatureFinal.csv',index=False)