In [163]:
import pandas as pd

In [164]:
batting = pd.read_csv("ODIBatting.csv")
batting.head(1)

,Player,Career Span,Career Start,Career End,Matches Played,Innings Batted,Not Outs,Runs Scored,Highest Innings Score,Highest Innings Score Num,...,Balls Faced,Batting Strike Rate,Hundreds Scored,Scores Of Fifty Or More,Ducks Scored,Country,Player Count,5000+ Runs Scored,40+ Batting Avg,90+ Batting Strike Rate
0,EJG Morgan (2009-2018),2009-2018,2009,2018,189,176,27,5813,124*,124,...,6310,92.12,10,36,11,England,1,1,0,1

In [165]:
batting = batting.rename(columns={"Career End" : "Career_End", "Runs Scored" : "Runs", "Highest Innings Score Num" : "Highest Score", "Hundreds Scored" : "Centuries", "Ducks Scored" : "Ducks", "Batting Strike Rate" : "Strike Rate", "Scores Of Fifty Or More" : "Half Centuries"})
batting = batting.drop(batting[batting.Career_End < 2018].index)
batting.head()

,Player,Career Span,Career Start,Career_End,Matches Played,Innings Batted,Not Outs,Runs,Highest Innings Score,Highest Score,...,Balls Faced,Strike Rate,Centuries,Half Centuries,Ducks,Country,Player Count,5000+ Runs Scored,40+ Batting Avg,90+ Batting Strike Rate
0,EJG Morgan (2009-2018),2009-2018,2009,2018,189,176,27,5813,124*,124,...,6310,92.12,10,36,11,England,1,1,0,1
3,JE Root (2013-2018),2013-2018,2013,2018,121,115,19,4946,133*,133,...,5722,86.43,13,29,4,England,1,0,1,0
14,JC Buttler (2012-2018),2012-2018,2012,2018,122,101,21,3176,129,129,...,2715,116.97,6,18,11,England,1,0,0,1
18,JJ Roy (2015-2018),2015-2018,2015,2018,70,69,2,2536,180,180,...,2433,104.23,6,12,7,England,1,0,0,1
22,AD Hales (2014-2018),2014-2018,2014,2018,67,65,3,2314,171,171,...,2419,95.65,6,13,5,England,1,0,0,1

In [166]:
battingFeatures = batting.drop(columns=['Career Span', 'Career Start', 'Career_End', 'Highest Innings Score', 'Player Count', '40+ Batting Avg', 'Country', '90+ Batting Strike Rate', '5000+ Runs Scored' ])
def removeYear(x):
    return x[:-12]
def removeNA(x):
    if(x == '-'):
        return 0
    return x

battingFeatures["Player"] = battingFeatures["Player"].apply(removeYear)
battingFeatures["Innings Batted"] = battingFeatures["Innings Batted"].apply(removeNA)
battingFeatures["Not Outs"] = battingFeatures["Not Outs"].apply(removeNA)
battingFeatures["Runs"] = battingFeatures["Runs"].apply(removeNA)
battingFeatures["Highest Score"] = battingFeatures["Highest Score"].apply(removeNA)
battingFeatures["Batting Avg"] = battingFeatures["Batting Avg"].apply(removeNA)
battingFeatures["Balls Faced"] = battingFeatures["Balls Faced"].apply(removeNA)
battingFeatures["Strike Rate"] = battingFeatures["Strike Rate"].apply(removeNA)
battingFeatures["Centuries"] = battingFeatures["Centuries"].apply(removeNA)
battingFeatures["Half Centuries"] = battingFeatures["Half Centuries"].apply(removeNA)
battingFeatures["Ducks"] = battingFeatures["Ducks"].apply(removeNA)

battingFeatures["Player"] = battingFeatures["Player"].astype(str)
battingFeatures["Innings Batted"] = pd.to_numeric(battingFeatures["Innings Batted"])
battingFeatures["Not Outs"] = pd.to_numeric(battingFeatures["Not Outs"])
battingFeatures["Runs"] = pd.to_numeric(battingFeatures["Runs"])
battingFeatures["Highest Score"] = pd.to_numeric(battingFeatures["Highest Score"])
battingFeatures["Batting Avg"] = pd.to_numeric(battingFeatures["Batting Avg"])
battingFeatures["Balls Faced"] = pd.to_numeric(battingFeatures["Balls Faced"])
battingFeatures["Strike Rate"] = pd.to_numeric(battingFeatures["Strike Rate"])
battingFeatures["Centuries"] = pd.to_numeric(battingFeatures["Centuries"])
battingFeatures["Half Centuries"] = pd.to_numeric(battingFeatures["Half Centuries"])
battingFeatures["Ducks"] = pd.to_numeric(battingFeatures["Ducks"])


battingFeatures.head()

,Player,Matches Played,Innings Batted,Not Outs,Runs,Highest Score,Batting Avg,Balls Faced,Strike Rate,Centuries,Half Centuries,Ducks
0,EJG Morgan,189,176,27,5813,124,39.01,6310,92.12,10,36,11
3,JE Root,121,115,19,4946,133,51.52,5722,86.43,13,29,4
14,JC Buttler,122,101,21,3176,129,39.70,2715,116.97,6,18,11
18,JJ Roy,70,69,2,2536,180,37.85,2433,104.23,6,12,7
22,AD Hales,67,65,3,2314,171,37.32,2419,95.65,6,13,5

In [167]:
battingFeatures.shape

(277, 12)

In [168]:
battingFeatures.dtypes

Player             object
Matches Played      int64
Innings Batted      int64
Not Outs            int64
Runs                int64
Highest Score       int64
Batting Avg       float64
Balls Faced         int64
Strike Rate       float64
Centuries           int64
Half Centuries      int64
Ducks               int64
dtype: object

In [169]:
battingFeatures = battingFeatures.sort_values(by=['Runs'], ascending=False)
battingFeatures.head()

,Player,Matches Played,Innings Batted,Not Outs,Runs,Highest Score,Batting Avg,Balls Faced,Strike Rate,Centuries,Half Centuries,Ducks
992,V Kohli,216,208,37,10232,183,59.83,11016,92.88,38,48,12
993,MS Dhoni,329,278,77,9999,183,49.74,11435,87.44,9,67,9
607,CH Gayle,281,276,17,9672,215,37.34,11274,85.79,23,48,23
478,AB de Villiers,223,213,39,9427,176,54.17,9308,101.27,25,52,7
795,LRPL Taylor,210,195,34,7714,181,47.91,9274,83.17,20,45,9

In [170]:
battingFeatures = battingFeatures.reset_index(drop=True)
battingFeatures.head()

,Player,Matches Played,Innings Batted,Not Outs,Runs,Highest Score,Batting Avg,Balls Faced,Strike Rate,Centuries,Half Centuries,Ducks
0,V Kohli,216,208,37,10232,183,59.83,11016,92.88,38,48,12
1,MS Dhoni,329,278,77,9999,183,49.74,11435,87.44,9,67,9
2,CH Gayle,281,276,17,9672,215,37.34,11274,85.79,23,48,23
3,AB de Villiers,223,213,39,9427,176,54.17,9308,101.27,25,52,7
4,LRPL Taylor,210,195,34,7714,181,47.91,9274,83.17,20,45,9

In [171]:
temp =pd.read_csv("battingFeaturesRating.csv")
temp.head()
battingFeatures["Rating"] = temp["Rating"]
battingFeatures = battingFeatures.sort_values(by=['Rating'], ascending=False)
battingFeatures = battingFeatures.reset_index(drop=True)
battingFeatures

,Player,Matches Played,Innings Batted,Not Outs,Runs,Highest Score,Batting Avg,Balls Faced,Strike Rate,Centuries,Half Centuries,Ducks,Rating
0,V Kohli,216,208,37,10232,183,59.83,11016,92.88,38,48,12,890
1,MS Dhoni,329,278,77,9999,183,49.74,11435,87.44,9,67,9,875
2,CH Gayle,281,276,17,9672,215,37.34,11274,85.79,23,48,23,870
3,AB de Villiers,223,213,39,9427,176,54.17,9308,101.27,25,52,7,865
4,LRPL Taylor,210,195,34,7714,181,47.91,9274,83.17,20,45,9,830
5,HM Amla,169,166,11,7696,159,49.65,8618,89.30,26,36,4,828
6,RG Sharma,193,187,31,7454,264,47.78,8406,88.67,21,37,12,825
7,Q de Kock,98,98,5,4133,178,44.44,4381,94.33,13,17,2,803
8,F du Plessis,124,119,15,4693,185,45.12,5298,88.58,10,29,3,801
9,JE Root,121,115,19,4946,133,51.52,5722,86.43,13,29,4,791
10,Babar Azam,54,52,8,2267,125,51.52,2674,84.77,8,9,2,781
11,MJ Guptill,162,159,17,6129,237,43.16,7077,86.60,14,34,13,750
12,SD Hope,44,41,6,1662,146,47.48,2320,71.63,4,7,4,744
13,AJ Finch,96,92,1,3418,148,37.56,3817,89.54,11,18,8,744
14,KS Williamson,132,126,11,5316,145,46.22,6384,83.27,11,35,5,736
15,Fakhar Zaman,26,26,4,1275,210,57.95,1305,97.70,3,8,2,736
16,S Dhawan,115,114,6,4935,137,45.69,5234,94.28,15,25,3,732
17,JC Buttler,122,101,21,3176,129,39.70,2715,116.97,6,18,11,710
18,JM Bairstow,54,50,8,2017,141,48.02,1929,104.56,6,7,2,691
19,EJG Morgan,189,176,27,5813,124,39.01,6310,92.12,10,36,11,690
20,Mushfiqur Rahim,198,184,31,5346,144,34.94,6881,77.69,6,32,10,689
21,Tamim Iqbal,186,184,8,6450,154,36.64,8254,78.14,11,44,16,679
22,Usman Shinwari,9,1,0,0,0,0.00,1,0.00,0,0,1,1
23,C Overton,1,0,0,0,0,0.00,0,0.00,0,0,0,1
24,CAK Rajitha,3,0,0,0,0,0.00,0,0.00,0,0,0,1
25,Fazle Mahmud,2,2,0,0,0,0.00,9,0.00,0,0,2,1
26,C Hemraj,6,6,0,82,32,13.66,98,83.67,0,0,0,1
27,T Shamsi,11,3,2,0,0,0.00,2,0.00,0,0,1,1
28,PWA Mulder,7,7,3,57,19,14.25,78,73.07,0,0,0,1
29,Mohammad Saifuddin,7,4,1,80,50,26.66,114,70.17,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,S Prasanna,40,37,3,421,95,12.38,445,94.60,0,2,7,0
248,Shafiqullah,24,21,2,430,56,22.63,408,105.39,0,2,4,0
249,TG Southee,137,83,30,660,55,12.45,658,100.30,0,1,12,0
250,Imam-ul-Haq,16,16,3,819,128,63.00,1001,81.81,4,3,1,0
251,HM Nicholls,33,31,9,814,124,37.00,913,89.15,1,6,4,0
252,MJ Santner,53,42,15,771,67,28.55,846,91.13,0,2,3,0
253,SO Hetmyer,20,20,0,758,127,37.90,709,106.91,3,2,1,0
254,Gulbadin Naib,49,41,8,757,82,22.93,1061,71.34,0,5,5,0
255,AG Cremer,96,71,20,744,58,14.58,1196,62.20,0,1,7,0
256,MP Stoinis,21,21,4,721,146,42.41,734,98.22,1,5,1,0
257,PJ Moor,42,39,3,698,52,19.38,1089,64.09,0,3,2,0
258,Rashid Khan,52,38,7,676,60,21.80,668,101.19,0,3,2,0
259,Hashmatullah Shahidi,25,25,5,675,97,33.75,1057,63.85,0,5,3,0
260,HH Pandya,42,27,4,670,83,29.13,585,114.52,0,4,2,0
261,R Powell,34,31,3,670,101,23.92,806,83.12,1,2,2,0
262,DM de Silva,28,26,4,593,84,26.95,741,80.02,0,4,2,0
263,GH Dockrell,77,49,22,436,62,16.14,612,71.24,0,1,4,0
264,LE Plunkett,74,44,15,582,56,20.06,585,99.48,0,1,3,0
265,DAS Gunaratne,31,25,4,575,114,27.38,724,79.41,1,1,0,0
266,BJ Watling,28,25,2,573,96,24.91,838,68.37,0,5,3,0
267,Mominul Haque,28,26,1,557,60,22.28,749,74.36,0,3,1,0
268,JN Mohammed,28,24,1,551,91,23.95,795,69.30,0,4,2,0
269,SL Malinga,213,109,34,534,56,7.12,697,76.61,0,1,25,0
270,AU Rashid,78,34,9,514,69,20.56,501,102.59,0,1,2,0
271,Liton Das,24,24,1,505,121,21.95,621,81.32,1,1,4,0
272,Dawlat Zadran,72,49,25,500,47,20.83,624,80.12,0,0,5,0
273,Imad Wasim,32,22,9,480,63,36.92,508,94.48,0,4,1,0
274,B Kumar,95,44,14,440,53,14.66,598,73.57,0,1,7,0
275,MK Pandey,23,18,6,440,104,36.66,479,91.85,1,2,2,0
276,TK Musakanda,15,15,1,304,60,21.71,382,79.58,0,1,1,0

In [172]:
#Count number of rated players
ratedPlayerCount = len(battingFeatures[battingFeatures.Rating > 0].index)

#Define training and testing data
X_train = battingFeatures.drop(columns=['Player', 'Rating'])
X_test = X_train.iloc[ratedPlayerCount:,:]
X_train = X_train.iloc[:ratedPlayerCount,:]

#store ratings in y_train
y_train = battingFeatures['Rating']
y_train = y_train.iloc[:ratedPlayerCount]

In [173]:
#Random Forest
from sklearn.ensemble import RandomForestRegressor 

regr = RandomForestRegressor(max_depth=2, random_state=0, n_estimators=100)
regr.fit(X_train, y_train)
print(regr.feature_importances_)
RFresults = regr.predict(X_test)
'''
clf = RandomForestClassifier(n_estimators=100, max_depth=2, random_state=0)
clf = clf.fit(X_train, y_train)
RFresults = clf.predict(X_test)'''

battingFeatures["Rating"][ratedPlayerCount:] = RFresults

[0.01997281 0.11913551 0.00056661 0.13225996 0.11092959 0.18726835
 0.11269021 0.00984756 0.10991866 0.19741073 0.        ]

C:\Users\parek\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]

In [174]:
battingFeatures = battingFeatures.sort_values(by=['Rating'], ascending=False)
battingFeatures = battingFeatures.reset_index(drop=True)
battingFeatures

,Player,Matches Played,Innings Batted,Not Outs,Runs,Highest Score,Batting Avg,Balls Faced,Strike Rate,Centuries,Half Centuries,Ducks,Rating
0,V Kohli,216,208,37,10232,183,59.83,11016,92.88,38,48,12,890.000000
1,MS Dhoni,329,278,77,9999,183,49.74,11435,87.44,9,67,9,875.000000
2,CH Gayle,281,276,17,9672,215,37.34,11274,85.79,23,48,23,870.000000
3,AB de Villiers,223,213,39,9427,176,54.17,9308,101.27,25,52,7,865.000000
4,LRPL Taylor,210,195,34,7714,181,47.91,9274,83.17,20,45,9,830.000000
5,HM Amla,169,166,11,7696,159,49.65,8618,89.30,26,36,4,828.000000
6,RG Sharma,193,187,31,7454,264,47.78,8406,88.67,21,37,12,825.000000
7,Shoaib Malik,274,246,40,7284,143,35.35,8910,81.75,9,43,13,813.070195
8,WU Tharanga,231,219,17,6926,174,34.28,9108,76.04,15,37,17,811.659132
9,Q de Kock,98,98,5,4133,178,44.44,4381,94.33,13,17,2,803.000000
10,F du Plessis,124,119,15,4693,185,45.12,5298,88.58,10,29,3,801.000000
11,JE Root,121,115,19,4946,133,51.52,5722,86.43,13,29,4,791.000000
12,Babar Azam,54,52,8,2267,125,51.52,2674,84.77,8,9,2,781.000000
13,DA Warner,106,104,4,4343,179,43.43,4498,96.55,14,17,2,757.696386
14,PR Stirling,100,98,2,3346,177,34.85,3720,89.94,7,16,9,753.609153
15,SPD Smith,108,94,12,3431,164,41.84,3973,86.35,8,19,5,750.271685
16,MJ Guptill,162,159,17,6129,237,43.16,7077,86.60,14,34,13,750.000000
17,SK Raina,226,194,35,5615,116,35.31,6005,93.50,5,36,14,749.848946
18,AD Hales,67,65,3,2314,171,37.32,2419,95.65,6,13,5,746.609153
19,JJ Roy,70,69,2,2536,180,37.85,2433,104.23,6,12,7,746.609153
20,Mohammad Hafeez,203,202,14,6153,140,32.72,8143,75.56,11,34,18,746.336271
21,BRM Taylor,188,187,15,6156,145,35.79,8085,76.14,10,36,14,746.108119
22,SD Hope,44,41,6,1662,146,47.48,2320,71.63,4,7,4,744.000000
23,AJ Finch,96,92,1,3418,148,37.56,3817,89.54,11,18,8,744.000000
24,EC Joyce,61,60,8,2151,160,41.36,2921,73.63,5,12,4,739.590061
25,MN Samuels,207,196,26,5606,133,32.97,7463,75.11,10,30,11,738.212172
26,Mahmudullah,168,145,38,3637,128,33.99,4784,76.02,3,20,8,738.074142
27,JP Duminy,192,174,39,5016,150,37.15,5959,84.17,4,27,7,738.074142
28,Shakib Al Hasan,195,183,24,5577,134,35.07,6863,81.26,7,40,10,736.393462
29,KS Williamson,132,126,11,5316,145,46.22,6384,83.27,11,35,5,736.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,O Thomas,4,2,1,0,0,0.00,4,0.00,0,0,1,1.000000
248,OC McCoy,2,1,1,0,0,0.00,1,0.00,0,0,0,1.000000
249,B Muzarabani,18,15,7,16,7,2.00,89,17.97,0,0,5,1.000000
250,LH Ferguson,21,10,5,44,19,8.80,94,46.80,0,0,2,1.000000
251,PKD Chase,25,16,6,35,14,3.50,56,62.50,0,0,7,1.000000
252,RL Chase,11,9,1,117,33,14.62,182,64.28,0,0,2,1.000000
253,CBRLS Kumara,8,5,3,16,7,8.00,37,43.24,0,0,0,1.000000
254,PADLR Sandakan,19,10,4,28,6,4.66,77,36.36,0,0,1,1.000000
255,FA Allen,4,4,0,25,10,6.25,52,48.07,0,0,0,1.000000
256,JA Richardson,4,3,1,21,14,10.50,34,61.76,0,0,0,1.000000
257,Najmul Hossain Shanto,3,3,0,20,7,6.66,45,44.44,0,0,0,1.000000
258,KOK Williams,8,5,4,19,16,19.00,27,70.37,0,0,0,1.000000
259,LN Roche,3,2,0,4,4,2.00,10,40.00,0,0,1,1.000000
260,KK Ahmed,6,2,1,4,3,4.00,12,33.33,0,0,0,1.000000
261,B Stanlake,6,4,2,4,2,2.00,26,15.38,0,0,0,1.000000
262,Nazmul Islam,5,1,0,7,7,7.00,13,53.84,0,0,0,1.000000
263,MG Neser,2,2,0,8,6,4.00,16,50.00,0,0,0,1.000000
264,Mehidy Hasan Miraz,22,13,2,212,51,19.27,324,65.43,0,1,0,1.000000
265,MS Chapman,3,3,0,9,8,3.00,23,39.13,0,0,1,1.000000
266,MA Aponso,9,7,4,10,4,3.33,45,22.22,0,0,1,1.000000
267,Abul Hasan,7,3,0,11,7,3.66,16,68.75,0,0,0,1.000000
268,SS Cottrell,6,4,2,14,8,7.00,24,58.33,0,0,0,1.000000
269,Shaheen Shah Afridi,6,2,1,14,14,14.00,22,63.63,0,0,1,1.000000
270,Ihsanullah,16,16,2,307,57,21.92,440,69.77,0,3,2,1.000000
271,WP Masakadza,17,10,1,53,15,5.88,125,42.40,0,0,3,1.000000
272,BB Chari,10,10,0,131,39,13.10,305,42.95,0,0,0,1.000000
273,TS Chisoro,18,15,6,134,42,14.88,218,61.46,0,0,2,1.000000
274,Umar Amin,16,16,1,271,59,18.06,392,69.13,0,1,0,1.000000
275,RP Burl,13,11,2,139,30,15.44,224,62.05,0,0,1,1.000000
276,R Ngarava,9,6,1,14,10,2.80,30,46.66,0,0,2,1.000000

In [175]:
bowling=pd.read_csv("bowlingFeatureFinal.csv")
bowling

,Player,Innings Bowled In,Balls Bowled,Runs Conceded,Wickets Taken,Bowling Avg,Economy Rate,Bowling Strike Rate,Ratings
0,SL Malinga,207,102732,9145,318,28.75,5.34,32.3,874.000000
1,DW Steyn,118,60138,4893,190,25.75,4.88,31.6,861.000000
2,Mashrafe Mortaza,200,10005,7985,257,31.07,4.78,38.9,856.000000
3,JJ Bumrah,44,2212,1639,78,21.01,4.44,28.3,835.000000
4,NLTC Perera,139,52524,5148,165,31.20,5.87,31.8,812.626938
5,Dawlat Zadran,70,32706,2914,98,29.73,5.34,33.3,810.671021
6,RAS Lakmal,79,36852,3321,105,31.62,5.40,35.1,810.671021
7,Shakib Al Hasan,192,9897,7333,247,29.68,4.44,40.0,810.000000
8,TL Chatara,62,30366,2636,85,31.01,5.20,35.7,809.708294
9,K Rabada,56,29106,2428,93,26.10,5.00,31.3,809.608294
10,KJ O'Brien,107,40878,3575,112,31.91,5.24,36.5,809.177818
11,Rubel Hossain,93,42324,3955,121,32.68,5.60,34.9,805.699447
12,Mohammed Shami,51,2645,2449,94,26.05,5.55,28.1,805.647728
13,CR Woakes,77,3768,3463,113,30.64,5.51,33.3,805.647728
14,AU Rashid,74,3940,3620,119,30.42,5.51,33.1,805.647728
15,LE Plunkett,73,3501,3424,115,29.77,5.86,30.4,805.647728
16,KAJ Roach,79,3967,3312,114,29.05,5.00,34.7,804.585000
17,Junaid Khan,71,3325,2896,104,27.84,5.22,31.9,804.585000
18,MA Starc,75,3761,3109,145,21.44,4.95,25.9,804.135000
19,Imran Tahir,89,46998,3675,151,24.33,4.69,31.1,800.000000
20,TA Boult,71,3842,3326,129,25.78,5.19,29.7,800.000000
21,Rashid Khan,50,26226,1708,118,14.47,3.90,22.2,800.000000
22,AG Cremer,95,4680,3597,119,30.22,4.61,39.3,794.057056
23,WB Rankin,52,2616,2067,74,27.93,4.74,35.3,791.156167
24,B Kumar,94,4552,3784,99,38.22,4.98,45.9,790.000000
25,AD Russell,51,2176,2128,65,32.73,5.86,33.4,785.353153
26,JO Holder,84,4058,3702,112,33.05,5.47,36.2,784.094847
27,UT Yadav,73,3558,3565,106,33.63,6.01,33.5,783.994847
28,TG Southee,135,6870,6202,179,34.64,5.41,38.3,779.311986
29,RA Jadeja,140,7255,5905,169,34.94,4.88,42.9,770.000000
...,...,...,...,...,...,...,...,...,...
252,DM Bravo,0,0,0,0,0.00,0.00,0.0,1.153049
253,NJ O'Brien,0,0,0,0,0.00,0.00,0.0,1.153049
254,JJ Roy,0,0,0,0,0.00,0.00,0.0,1.153049
255,WU Tharanga,0,0,0,0,0.00,0.00,0.0,1.153049
256,KD Karthik,0,0,0,0,0.00,0.00,0.0,1.153049
257,RR Hendricks,0,0,0,0,0.00,0.00,0.0,1.153049
258,KL Rahul,0,0,0,0,0.00,0.00,0.0,1.153049
259,GC Wilson,0,0,0,0,0.00,0.00,0.0,1.153049
260,BJ Watling,0,0,0,0,0.00,0.00,0.0,1.153049
261,Liton Das,0,0,0,0,0.00,0.00,0.0,1.153049
262,MK Pandey,0,0,0,0,0.00,0.00,0.0,1.153049
263,Shafiqullah,0,0,0,0,0.00,0.00,0.0,1.153049
264,AM Rahane,0,0,0,0,0.00,0.00,0.0,1.153049
265,MDKJ Perera,0,0,0,0,0.00,0.00,0.0,1.153049
266,TWM Latham,0,0,0,0,0.00,0.00,0.0,1.153049
267,CR Ervine,0,0,0,0,0.00,0.00,0.0,1.153049
268,EC Joyce,0,0,0,0,0.00,0.00,0.0,1.153049
269,JM Bairstow,0,0,0,0,0.00,0.00,0.0,1.153049
270,HM Amla,0,0,0,0,0.00,0.00,0.0,1.153049
271,Najmul Hossain Shanto,0,0,0,0,0.00,0.00,0.0,1.000000
272,Hazratullah Zazai,0,0,0,0,0.00,0.00,0.0,1.000000
273,FA Allen,4,138,131,0,0.00,5.69,0.0,1.000000
274,S Kaul,3,162,179,0,0.00,6.62,0.0,1.000000
275,Fazle Mahmud,1,18,16,0,0.00,5.33,0.0,1.000000
276,NGRP Jayasuriya,2,96,95,0,0.00,5.93,0.0,1.000000
277,Abul Hasan,7,216,244,0,0.00,6.77,0.0,1.000000
278,MS Chapman,0,0,0,0,0.00,0.00,0.0,1.000000
279,C Jonker,0,0,0,0,0.00,0.00,0.0,1.000000
280,TL Seifert,0,0,0,0,0.00,0.00,0.0,1.000000
281,TS Kamunhukamwe,0,0,0,0,0.00,0.00,0.0,1.000000

In [176]:
Final = pd.merge(battingFeatures, bowling, how='inner', on = 'Player')
Final=Final.drop(columns=['Matches Played','Innings Batted','Not Outs','Runs','Highest Score','Batting Avg','Balls Faced','Strike Rate','Centuries','Half Centuries','Ducks'])
Final=Final.drop(columns=['Innings Bowled In','Balls Bowled','Runs Conceded','Wickets Taken','Bowling Avg','Economy Rate','Bowling Strike Rate'])
Final=Final.rename(index=str, columns={"Rating": "Batting Ratings", "Ratings": "Bowling Ratings"})
Final['Overall Rating']=Final['Batting Ratings']+Final['Bowling Ratings']
Final=Final.sort_values(by=['Overall Rating'], ascending=False)
Final

                    Player  Batting Ratings  Bowling Ratings  Overall Rating
29         Shakib Al Hasan       736.393462       810.000000     1546.393462
7             Shoaib Malik       813.070195       702.995934     1516.066129
2                 CH Gayle       870.000000       620.000000     1490.000000
61              KJ O'Brien       673.640904       809.177818     1482.818722
37               BA Stokes       732.578099       730.414781     1462.992880
43              AD Mathews       720.697850       733.503568     1454.201418
20         Mohammad Hafeez       746.336271       707.063569     1453.399841
26              MN Samuels       738.212172       712.914819     1451.126991
28               JP Duminy       738.074142       712.189174     1450.263315
27             Mahmudullah       738.074142       711.126446     1449.200588
47             SC Williams       710.589982       706.368153     1416.958134
35           Sikandar Raza       732.578099       683.474303     1416.052402
14             PR Stirling       753.609153       646.349026     1399.958179
73               RA Jadeja       559.433052       770.000000     1329.433052
80             NLTC Perera       512.053336       812.626938     1324.680274
71           Mohammad Nabi       570.527415       748.938488     1319.465902
11                 JE Root       791.000000       524.637626     1315.637626
68                  MM Ali       607.791904       705.746486     1313.538390
79               JO Holder       526.615061       784.094847     1310.709909
70            E Chigumbura       592.110604       718.379174     1310.489777
17                SK Raina       749.848946       559.079264     1308.928209
30           KS Williamson       736.000000       558.159368     1294.159368
65                MR Marsh       644.401256       643.201448     1287.602704
64              GJ Maxwell       651.401256       613.950880     1265.352136
99               CR Woakes       417.455398       805.647728     1223.103126
62             H Masakadza       660.060781       557.476832     1217.537613
96              AD Russell       425.342096       785.353153     1210.695249
0                  V Kohli       890.000000       293.861759     1183.861759
72      Samiullah Shinwari       563.172415       600.138153     1163.310567
106       Mashrafe Mortaza       285.853408       856.000000     1141.853408
..                     ...              ...              ...             ...
173            Shafiqullah        30.035014         1.153049       31.188063
174               JM Vince        29.944225         1.153049       31.097274
175        Mohammad Mithun        29.944225         1.153049       31.097274
176              H Klaasen        22.655278         1.153049       23.808327
178               R Murray        22.589225         1.153049       23.742274
189           TK Musakanda         8.355000         9.345548       17.700548
212               C Zhuwao         8.355000         9.329358       17.684358
233               C Hemraj         1.000000         9.366590       10.366590
224                RR Pant         8.355000         2.000000       10.355000
245           Ariful Haque         1.000000         9.345548       10.345548
249            PS Masvaure         1.000000         9.345548       10.345548
231              C Overton         1.000000         9.340635       10.340635
279              Umar Amin         1.000000         9.333326       10.333326
207       S Samarawickrama         8.355000         1.153049        9.508049
209            SW Billings         8.355000         1.153049        9.508049
197                CA Lynn         8.355000         1.153049        9.508049
222               C Jonker         8.355000         1.000000        9.355000
196        NGRP Jayasuriya         8.355000         1.000000        9.355000
218      Hazratullah Zazai         8.355000         1.000000        9.355000
216             TL Seifert         8.355000         1.000000        9.355000
214        TS Kamunhukamwe         8.355000         1.000000        9.355000
277               BB Chari         1.000000         1.153049        2.153049
246             SW Poynter         1.000000         1.153049        2.153049
275             Ihsanullah         1.000000         1.153049        2.153049
270             MS Chapman         1.000000         1.000000        2.000000
229           Fazle Mahmud         1.000000         1.000000        2.000000
272             Abul Hasan         1.000000         1.000000        2.000000
250                 S Kaul         1.000000         1.000000        2.000000
262  Najmul Hossain Shanto         1.000000         1.000000        2.000000
260               FA Allen         1.000000         1.000000        2.000000

[282 rows x 4 columns]

In [177]:
import random
Teams={'CSK':[],'MI':[],'RCB':[],'SRH':[],'KXIP':[],'DC':[],'KKR':[],'RR':[]}
Team=[]
FinalList = list(Final['Player'])
count=0
#Snake Draft implementation
for key in Teams:
    Team.append(key)
for i in range(0,6):
    random.shuffle(Team)
    for j in Team:
        Teams[j].append(FinalList[count])
        count=count+1
    print("Order of selection by Snake Draft System is",Team)

    for j in reversed(Team):
        Teams[j].append(FinalList[count])
        count=count+1
    print("Order of selection by Snake Draft System is",Team[::-1])

Order of selection by Snake Draft System is ['KXIP', 'SRH', 'KKR', 'MI', 'RCB', 'RR', 'CSK', 'DC']
Order of selection by Snake Draft System is ['DC', 'CSK', 'RR', 'RCB', 'MI', 'KKR', 'SRH', 'KXIP']
Order of selection by Snake Draft System is ['CSK', 'KXIP', 'SRH', 'DC', 'RCB', 'KKR', 'MI', 'RR']
Order of selection by Snake Draft System is ['RR', 'MI', 'KKR', 'RCB', 'DC', 'SRH', 'KXIP', 'CSK']
Order of selection by Snake Draft System is ['KXIP', 'SRH', 'RR', 'MI', 'RCB', 'KKR', 'DC', 'CSK']
Order of selection by Snake Draft System is ['CSK', 'DC', 'KKR', 'RCB', 'MI', 'RR', 'SRH', 'KXIP']
Order of selection by Snake Draft System is ['MI', 'RCB', 'KKR', 'DC', 'RR', 'KXIP', 'SRH', 'CSK']
Order of selection by Snake Draft System is ['CSK', 'SRH', 'KXIP', 'RR', 'DC', 'KKR', 'RCB', 'MI']
Order of selection by Snake Draft System is ['MI', 'KXIP', 'SRH', 'KKR', 'CSK', 'DC', 'RCB', 'RR']
Order of selection by Snake Draft System is ['RR', 'RCB', 'DC', 'CSK', 'KKR', 'SRH', 'KXIP', 'MI']
Order of selection by Snake Draft System is ['KKR', 'MI', 'RCB', 'KXIP', 'DC', 'RR', 'SRH', 'CSK']
Order of selection by Snake Draft System is ['CSK', 'SRH', 'RR', 'DC', 'KXIP', 'RCB', 'MI', 'KKR']

In [178]:
FinalTeams=pd.DataFrame.from_dict(Teams)
FinalTeams

,CSK,MI,RCB,SRH,KXIP,DC,KKR,RR
0,Mohammad Hafeez,KJ O'Brien,BA Stokes,Shoaib Malik,Shakib Al Hasan,MN Samuels,CH Gayle,AD Mathews
1,Mahmudullah,PR Stirling,Sikandar Raza,NLTC Perera,Mohammad Nabi,JP Duminy,RA Jadeja,SC Williams
2,JE Root,MR Marsh,SK Raina,JO Holder,MM Ali,E Chigumbura,KS Williamson,GJ Maxwell
3,MS Dhoni,H Masakadza,V Kohli,Mashrafe Mortaza,RG Sharma,Samiullah Shinwari,AD Russell,CR Woakes
4,F du Plessis,SPD Smith,Rahmat Shah,JDS Neesham,Nasir Hossain,AG Cremer,CJ Chibhabha,AB de Villiers
5,MJ Santner,DW Steyn,Gulbadin Naib,AJ Finch,AT Rayudu,SL Malinga,MJ Guptill,BRM Taylor
6,LE Plunkett,SC Williams,CL White,RAS Lakmal,Dawlat Zadran,Azhar Ali,Fakhar Zaman,MA Starc
7,KAJ Roach,TM Head,TG Southee,Rubel Hossain,TL Chatara,AU Rashid,B Kumar,Rashid Khan
8,M Morkel,Soumya Sarkar,K Rabada,TA Boult,Imran Tahir,F Behardien,Junaid Khan,CB Mpofu
9,HM Amla,GH Dockrell,Mohammed Shami,A Balbirnie,Mohammad Amir,LRPL Taylor,MD Gunathilaka,JJ Bumrah
10,MN Waller,Asghar Afghan,Q de Kock,UT Yadav,HH Pandya,PJ Cummins,WU Tharanga,WB Rankin
11,TJ Murtagh,Hasan Ali,Mustafizur Rahman,Babar Azam,DA Warner,JR Hazlewood,AL Phehlukwayo,KM Jadhav